### ISSUE TITLE
fritzconnection depended plugins can't find fritzconnection module?

### ISSUE THREAD

**Issue by Celoxocis** [Tafkas/fritzbox-munin#21]
I'm not sure if this is a fritzconnection issue or a plugin issue.

I'm running a fresh munin install on Ubuntu 16.04 LTS with proper permissions setup and can see the fritzbox graphs in munin except for those two depended on the fritzconnection module.

```
pip install fritzconnection
Requirement already satisfied: fritzconnection in /home/nas/.local/lib/python2.7/site-packages
Requirement already satisfied: requests>=2.2.0 in /home/nas/.local/lib/python2.7/site-packages (from fritzconnection)
Requirement already satisfied: lxml>=3.2.5 in /home/nas/.local/lib/python2.7/site-packages (from fritzconnection)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/nas/.local/lib/python2.7/site-packages (from requests>=2.2.0->fritzconnection)
Requirement already satisfied: idna<2.7,>=2.5 in /home/nas/.local/lib/python2.7/site-packages (from requests>=2.2.0->fritzconnection)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/nas/.local/lib/python2.7/site-packages (from requests>=2.2.0->fritzconnection)
Requirement already satisfied: certifi>=2017.4.17 in /home/nas/.local/lib/python2.7/site-packages (from requests>=2.2.0->fritzconnection)
```

version check of fritzconnection:
```
$ fritzconnection

FritzConnection:
version:            0.6
model:              FRITZ!Box 7490
()
```

running manual test of the fritzbox_traffic plugin:
```
sudo munin-run fritzbox_traffic.py
Traceback (most recent call last):
  File "/etc/munin/plugins/fritzbox_traffic.py", line 20, in <module>
    from fritzconnection import FritzConnection
ImportError: No module named fritzconnection
```

running manual test of the fritzbox_connection_uptime plugin:

```
sudo munin-run fritzbox_connection_uptime.py
Traceback (most recent call last):
  File "/etc/munin/plugins/fritzbox_connection_uptime.py", line 20, in <module>
    from fritzconnection import FritzConnection
ImportError: No module named fritzconnection
```

Note the: **"ImportError: No module named fritzconnection"**

any idea what could cause this?

my fritzbox is a 7490 at fritzOS 6.83

**Comment by Celoxocis** [comment]
okay. found the issue...
had to install fritzconnection as root user as munin runs as root user.
for those coming across the issue:

```
$ sudo su
root# pip install fritzconnection
```
