### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by rforberger** [Tafkas/fritzbox-munin#34]
Hi,

when running the plugin fritzbox_cpu_temperature.py, I get the following error python message:

`/ # munin-run fritzbox_cpu_temperature.py
Traceback (most recent call last):
  File "/etc/munin/plugins/fritzbox_cpu_temperature.py", line 60, in <module>
    get_cpu_temperature()
  File "/etc/munin/plugins/fritzbox_cpu_temperature.py", line 34, in get_cpu_temperature
    data = json.loads(xhr_data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

Other fritzbox-munin plugins are running and I have my FritzBOX IP address and password in /etc/munin/plugin-conf.d/fritzbox .

I am using the FritzBOX Model 7362 SL with FritzOS 7.01 .

Any idea what could be wrong?

Best regards,
rforberger

**Comment by Tafkas** [comment]
For FritzOS 7.01 you have to use the tag https://github.com/Tafkas/fritzbox-munin/releases/tag/7.0.0

**Comment by rforberger** [comment]
Thanks, it worked.
