### ISSUE TITLE
Can not retrieve fritzbox traffic 

### ISSUE THREAD

**Issue by Hobbabobba** [Tafkas/fritzbox-munin#6]
I am using a Fritzbox 7360 with FritzOS 6.50

Installed the scripts for FritzOS 6.50, but whatever plugin i call, i just get 

`Couldn't retrieve fritzbox traffic`

I tried by using the command `sudo -u munin python /etc/munin/plugins/fritzbox_traffic.py`

Here is the part of my `/etc/munin/plugin-conf.d/munin-node`-file:

```
[fritzbox_*]
user munin
env.fritzbox_ip 192.168.0.1
env.fritzbox_password mypassword
```

Any idea, what I did wrong? I am using Ubuntu 14.04.4 LTS

**Comment by Tafkas** [comment]
Did you install fritzconnection with `pip install fritzconnection` ?

**Comment by Hobbabobba** [comment]
yes, and it shows data: if i try `./fritzconnection.py` (as an example) it returns

```
FritzConnection:
version:            0.4.6
model:              FRITZ!Box Fon WLAN 7360
()
```

**Comment by Tafkas** [comment]
If you start a python shell and run the following lines:  

```
from fritzconnection import FritzConnection

conn = FritzConnection(address='fritzbox_ip')
down_traffic = conn.call_action('WANCommonInterfaceConfig', 'GetTotalBytesReceived')['NewTotalBytesReceived']
print ('down.value %d' % down_traffic)
```

What is your output?

**Comment by Hobbabobba** [comment]
I am not sure, if i did everything right (just copied everything into the file `test.py` and started it with `python test.py`) but this is the output:

```
Traceback (most recent call last):
  File "./test.py", line 3, in <module>
    conn = FritzConnection(address='fritzbox_ip')
  File "/etc/munin/plugins/fritzconnection.py", line 313, in __init__
    self._read_descriptions(password)
  File "/etc/munin/plugins/fritzconnection.py", line 324, in _read_descriptions
    parser = FritzDescParser(self.address, self.port, descfile)
  File "/etc/munin/plugins/fritzconnection.py", line 190, in __init__
    tree = etree.parse(source)
  File "lxml.etree.pyx", line 3239, in lxml.etree.parse (src/lxml/lxml.etree.c:69955)
  File "parser.pxi", line 1748, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:102066)
  File "parser.pxi", line 1774, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:102330)
  File "parser.pxi", line 1678, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:101365)
  File "parser.pxi", line 1110, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:96817)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91275)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92461)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91722)
IOError: Error reading file 'http://fritzbox_ip:49000/igddesc.xml': failed to load external entity "http://fritzbox_ip:49000/igddesc.xml"
```

**Comment by Tafkas** [comment]
You have to put the IP address of your Fritzbox instead of 'fritzbox_ip'. If you haven't changed it it should be '192.168.178.1'

**Comment by Hobbabobba** [comment]
Outsch :) The output is
`down.value 331377717877`

**Comment by Hobbabobba** [comment]
I just tried with the script version for FritzOS 6.3 and it returns data:

if i try `sudo -u munin python /etc/munin/plugins/fritzbox_traffic.py` the output is

```
down.value 332061672621
up.value 346102380965
maxdown.value 56316000
maxup.value 10237000
```

But: no data shows on the Munin-graph. I restarted the daemon with `/etc/init.d/munin-node restart`

**Comment by Hobbabobba** [comment]
finally working! my mistake: i configured the settings in `/etc/munin/munin-node.conf` and `/etc/munin/plugin-conf.d/munin-node` - lesson learned: read the readme and follow it to the letter!
Thanks for your time!

**Comment by kunoSchlonz** [comment]
Hi - i have the same issue - but still its not working
./fritzconnection.p => works for me
but this one not: 
sudo -u munin python /etc/munin/plugins/fritzbox_traffic.py

any idea how to resolve or debug this ?
